/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.UIManager;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import Sesion.SesionUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DashBoard extends javax.swing.JFrame {

    private HomePanel homePanel;
    private PerfilPanel perfilPanel;

    /**
     * Creates new form PerfilForm
     */
    public DashBoard() {
        initComponents();

        homePanel = new HomePanel(this);
        perfilPanel = new PerfilPanel();
        SetDate();
        mostrarInicio();
        setResizable(false);
    }

    private void mostrarPanel(JPanel panelHijo) {
        panelContenido.removeAll();
        panelContenido.setLayout(new BorderLayout());
        panelContenido.add(
                panelHijo,
                BorderLayout.CENTER
        );
        panelContenido.revalidate();
        panelContenido.repaint();
    }

    public void mostrarInicio() {
        HomePanel homePanel = new HomePanel();
        mostrarPanel(homePanel);
    }

    public void mostrarPerfil() {
        perfilPanel.actualizarDatos();
        mostrarPanel(perfilPanel);
    }

    private void SetDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("EEEE, d 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    public void abrirNuevaPublicacion() {

        CrearPublicacionForm crearForm
                = new CrearPublicacionForm();

        crearForm.setLocationRelativeTo(this);

        crearForm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                mostrarInicio();
            }
        });

        crearForm.setVisible(true);
    }

    private void cerrarSesion() {

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea cerrar la sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        SesionUsuario.cerrarSesion();

        LoginForm login = new LoginForm();
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        div = new javax.swing.JSeparator();
        btnInicio = new javax.swing.JButton();
        btnLogo = new javax.swing.JButton();
        pnlNuevaPublicacion = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        pnlCerrarSesion = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        lblTituloSistema = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(245, 248, 252));
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.setPreferredSize(new java.awt.Dimension(1020, 680));

        menu.setBackground(new java.awt.Color(30, 64, 121));
        menu.setAlignmentY(5.0F);

        div.setBackground(new java.awt.Color(255, 255, 255));
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setPreferredSize(new java.awt.Dimension(50, 30));

        btnInicio.setBackground(new java.awt.Color(38, 77, 142));
        btnInicio.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicioIcon.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnInicio.setBorderPainted(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setIconTextGap(10);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnLogo.setBackground(new java.awt.Color(30, 64, 121));
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo sistema.png"))); // NOI18N
        btnLogo.setBorder(null);
        btnLogo.setBorderPainted(false);

        pnlNuevaPublicacion.setBackground(new java.awt.Color(38, 77, 142));
        pnlNuevaPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        pnlNuevaPublicacion.setForeground(new java.awt.Color(255, 255, 255));
        pnlNuevaPublicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/publicaciones icon.png"))); // NOI18N
        pnlNuevaPublicacion.setText("Nueva Publicacion");
        pnlNuevaPublicacion.setActionCommand("");
        pnlNuevaPublicacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        pnlNuevaPublicacion.setBorderPainted(false);
        pnlNuevaPublicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNuevaPublicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNuevaPublicacion.setIconTextGap(10);
        pnlNuevaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlNuevaPublicacionActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(38, 77, 142));
        btnPerfil.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user icon.png"))); // NOI18N
        btnPerfil.setText("Mi Perfil");
        btnPerfil.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPerfil.setBorderPainted(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(10);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        pnlCerrarSesion.setBackground(new java.awt.Color(38, 77, 142));
        pnlCerrarSesion.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        pnlCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        pnlCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarIcon.png"))); // NOI18N
        pnlCerrarSesion.setText("Cerrar sesión");
        pnlCerrarSesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        pnlCerrarSesion.setBorderPainted(false);
        pnlCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlCerrarSesion.setIconTextGap(10);
        pnlCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlNuevaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlNuevaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(pnlCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.setBackground(new java.awt.Color(130, 158, 201));

        lblTituloSistema.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblTituloSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSistema.setText("Sistema de interacción estudiantil Universitaria");

        dateText.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Fecha");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloSistema)
                    .addComponent(dateText))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblTituloSistema)
                .addGap(18, 18, 18)
                .addComponent(dateText)
                .addGap(23, 23, 23))
        );

        panelContenido.setBackground(new java.awt.Color(245, 248, 252));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnInicioActionPerformed

    private void pnlNuevaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlNuevaPublicacionActionPerformed
        CrearPublicacionForm crearForm
                = new CrearPublicacionForm();

        crearForm.setLocationRelativeTo(this);
        crearForm.setVisible(true);
    }//GEN-LAST:event_pnlNuevaPublicacionActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        mostrarPerfil();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void pnlCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_pnlCerrarSesionActionPerformed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        mostrarInicio();
    }//GEN-LAST:event_btnInicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();
        UIManager.put("Button.arc", 999);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel dateText;
    private javax.swing.JSeparator div;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblTituloSistema;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JButton pnlCerrarSesion;
    private javax.swing.JButton pnlNuevaPublicacion;
    // End of variables declaration//GEN-END:variables
}
