/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.PublicacionController;
import Modelo.DTO.PublicacionVista;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MisPublicacionesPanel extends javax.swing.JPanel {

    private PublicacionVista publicacion;
    private PublicacionController publicacionController;
    private PerfilPanel perfilPanel;

    /**
     * Creates new form MisPublicacionesPanel
     */
    public MisPublicacionesPanel() {
        initComponents();
    }
    public MisPublicacionesPanel(
        PublicacionVista publicacion,
        PerfilPanel perfilPanel
) {
    initComponents();

    this.publicacion = publicacion;
    this.perfilPanel = perfilPanel;
    this.publicacionController = new PublicacionController();

    lblTitulo.setText(publicacion.getTitulo());

    lblCategoria.setText(
            "Categoría: " + publicacion.getNombreCategoria()
    );

    if (publicacion.getFecha() != null) {

        DateTimeFormatter formato =
                DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        lblFecha.setText(
                "Fecha: " + publicacion.getFecha().format(formato)
        );

    } else {
        lblFecha.setText("Fecha no disponible");
    }

    txtContenido.setText(publicacion.getContenido());
    txtContenido.setCaretPosition(0);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();

        lblTitulo.setText("jLabel1");

        lblCategoria.setText("jLabel1");

        lblFecha.setText("jLabel1");

        txtContenido.setEditable(false);
        txtContenido.setColumns(20);
        txtContenido.setLineWrap(true);
        txtContenido.setRows(5);
        txtContenido.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtContenido);

        btnEliminar.setText("Eliminar Publicacion");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha)
                            .addComponent(lblCategoria)
                            .addComponent(lblTitulo))
                        .addGap(184, 184, 184)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addGap(18, 18, 18)
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar esta publicación?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );
    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }
    boolean eliminado =
            publicacionController.eliminarPublicacion(
                    publicacion.getIdPublicacion()
            );
    if (eliminado) {
        JOptionPane.showMessageDialog(
                this,
                "Publicación eliminada correctamente."
        );
        if (perfilPanel != null) {
            perfilPanel.actualizarPublicacionesUsuario();
        }
    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo eliminar la publicación.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
