/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.PublicacionController;
import Modelo.DTO.PublicacionVista;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MisPublicacionesPanel extends javax.swing.JPanel {

    private PublicacionVista publicacion;
    private PublicacionController publicacionController;
    private PerfilPanel perfilPanel;

    /**
     * Creates new form MisPublicacionesPanel
     */
    public MisPublicacionesPanel() {
        initComponents();
    }
    public MisPublicacionesPanel(
        PublicacionVista publicacion,
        PerfilPanel perfilPanel
) {
    initComponents();

    this.publicacion = publicacion;
    this.perfilPanel = perfilPanel;
    this.publicacionController = new PublicacionController();

    lblTitulo.setText(publicacion.getTitulo());

    lblCategoria.setText(
             publicacion.getNombreCategoria()
    );

    if (publicacion.getFecha() != null) {

        DateTimeFormatter formato =
                DateTimeFormatter.ofPattern("dd/MM/yyyy");

        lblFecha.setText(
                publicacion.getFecha().format(formato)
        );

    } else {
        lblFecha.setText("Fecha no disponible");
    }

    txtContenido.setText(publicacion.getContenido());
    txtContenido.setCaretPosition(0);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 58, 154));
        lblTitulo.setText("jLabel1");

        lblCategoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(0, 58, 154));
        lblCategoria.setText("jLabel1");

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(153, 153, 153));
        lblFecha.setText("jLabel1");

        txtContenido.setEditable(false);
        txtContenido.setBackground(new java.awt.Color(245, 248, 252));
        txtContenido.setColumns(20);
        txtContenido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtContenido.setLineWrap(true);
        txtContenido.setRows(5);
        txtContenido.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtContenido);

        btnEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 58, 154));
        btnEliminar.setText("Eliminar Publicacion");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFecha)
                            .addGap(18, 18, 18)
                            .addComponent(lblCategoria))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
                        .addComponent(btnEliminar)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblTitulo)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de eliminar esta publicación?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );
    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }
    boolean eliminado =
            publicacionController.eliminarPublicacion(
                    publicacion.getIdPublicacion()
            );
    if (eliminado) {
        JOptionPane.showMessageDialog(
                this,
                "Publicación eliminada correctamente."
        );
        if (perfilPanel != null) {
            perfilPanel.actualizarPublicacionesUsuario();
        }
    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo eliminar la publicación.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
