/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DTO.Usuario;
import Sesion.SesionUsuario;
import javax.swing.JOptionPane;
import Controlador.PublicacionController;
import Modelo.DTO.PublicacionVista;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author User
 */
public class PerfilPanel extends javax.swing.JPanel {

    private PublicacionController publicacionController;

    /**
     * Creates new form PerfilPanel
     */
    public PerfilPanel() {
        initComponents();
        publicacionController = new PublicacionController();

        cargarDatosUsuario();
        cargarPublicacionesUsuario();
    }

    private void cargarDatosUsuario() {

        Usuario usuarioActual
                = SesionUsuario.obtenerUsuario();

        if (usuarioActual == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay una sesión iniciada."
            );
            return;
        }
        txtNombre.setText(
                usuarioActual.getNombre()
        );
        txtCorreo.setText(
                usuarioActual.getCorreo()
        );
        txtCarrera.setText(
                usuarioActual.getCarrera()
        );
    }

    public void actualizarDatos() {
    cargarDatosUsuario();
    cargarPublicacionesUsuario();
}

    private void cargarPublicacionesUsuario() {

        panelMisPublicaciones.removeAll();

        panelMisPublicaciones.setLayout(
                new BoxLayout(
                        panelMisPublicaciones,
                        BoxLayout.Y_AXIS
                )
        );

        List<PublicacionVista> publicaciones
                = publicacionController.listarPublicacionesDelUsuario();

        if (publicaciones.isEmpty()) {

            panelMisPublicaciones.add(
                    new javax.swing.JLabel(
                            "Todavía no has creado publicaciones."
                    )
            );

        } else {

            for (PublicacionVista publicacion : publicaciones) {

                MisPublicacionesPanel tarjeta
                        = new MisPublicacionesPanel(
                                publicacion,
                                this
                        );

                tarjeta.setAlignmentX(
                        java.awt.Component.LEFT_ALIGNMENT
                );

                tarjeta.setMaximumSize(
                        new java.awt.Dimension(
                                Integer.MAX_VALUE,
                                tarjeta.getPreferredSize().height
                        )
                );

                panelMisPublicaciones.add(tarjeta);

                panelMisPublicaciones.add(
                        javax.swing.Box.createVerticalStrut(10)
                );
            }
        }

        panelMisPublicaciones.revalidate();
        panelMisPublicaciones.repaint();
    }

    public void actualizarPublicacionesUsuario() {
    cargarPublicacionesUsuario();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        lblMiperfil = new javax.swing.JLabel();
        lblinfoPerfil = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMisPublicaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 32, 94));
        lblCorreo.setText("Correo:");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(250, 251, 252));
        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.setName(""); // NOI18N

        lblCarrera.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(0, 32, 94));
        lblCarrera.setText("Carrera:");

        txtCarrera.setEditable(false);
        txtCarrera.setBackground(new java.awt.Color(250, 251, 252));
        txtCarrera.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCarrera.setToolTipText("");
        txtCarrera.setBorder(null);
        txtCarrera.setName(""); // NOI18N

        lblMiperfil.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMiperfil.setForeground(new java.awt.Color(0, 32, 94));
        lblMiperfil.setText("Mi perfil");

        lblinfoPerfil.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblinfoPerfil.setForeground(new java.awt.Color(0, 32, 94));
        lblinfoPerfil.setText("Consulta y gestiona tu información personal");

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 32, 94));
        lblNombre.setText("Nombre:");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(250, 251, 252));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setName(""); // NOI18N

        javax.swing.GroupLayout panelMisPublicacionesLayout = new javax.swing.GroupLayout(panelMisPublicaciones);
        panelMisPublicaciones.setLayout(panelMisPublicacionesLayout);
        panelMisPublicacionesLayout.setHorizontalGroup(
            panelMisPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        panelMisPublicacionesLayout.setVerticalGroup(
            panelMisPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelMisPublicaciones);

        jLabel1.setText("Mis Publicaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblCarrera)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMiperfil)
                    .addComponent(lblinfoPerfil)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblMiperfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinfoPerfil)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(11, 11, 11)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorreo)
                .addGap(11, 11, 11)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCarrera)
                .addGap(11, 11, 11)
                .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblMiperfil;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblinfoPerfil;
    private javax.swing.JPanel panelMisPublicaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
