/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DTO.Usuario;
import Sesion.SesionUsuario;
import javax.swing.JOptionPane;
import Controlador.PublicacionController;
import Modelo.DTO.PublicacionVista;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author User
 */
public class PerfilPanel extends javax.swing.JPanel {

    private PublicacionController publicacionController;

    /**
     * Creates new form PerfilPanel
     */
    public PerfilPanel() {
        initComponents();
        publicacionController = new PublicacionController();

        cargarDatosUsuario();
        cargarPublicacionesUsuario();
    }

    private void cargarDatosUsuario() {

        Usuario usuarioActual
                = SesionUsuario.obtenerUsuario();

        if (usuarioActual == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "No hay una sesión iniciada."
            );
            return;
        }
        txtNombre.setText(
                usuarioActual.getNombre()
        );
        txtCorreo.setText(
                usuarioActual.getCorreo()
        );
        txtCarrera.setText(
                usuarioActual.getCarrera()
        );
    }

    public void actualizarDatos() {
        cargarDatosUsuario();
        cargarPublicacionesUsuario();
    }

    private void cargarPublicacionesUsuario() {

        panelMisPublicaciones.removeAll();

        panelMisPublicaciones.setLayout(
                new BoxLayout(
                        panelMisPublicaciones,
                        BoxLayout.Y_AXIS
                )
        );

        List<PublicacionVista> publicaciones
                = publicacionController.listarPublicacionesDelUsuario();

        if (publicaciones.isEmpty()) {

            panelMisPublicaciones.setLayout(new java.awt.GridBagLayout());

            javax.swing.JLabel lblVacio = new javax.swing.JLabel("Todavía no has creado publicaciones.");
            lblVacio.setFont(new java.awt.Font("Century Gothic", java.awt.Font.PLAIN, 14));
            lblVacio.setForeground(new java.awt.Color(125, 129, 142));
            lblVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            panelMisPublicaciones.add(lblVacio);

        } else {

            for (PublicacionVista publicacion : publicaciones) {

                MisPublicacionesPanel tarjeta
                        = new MisPublicacionesPanel(
                                publicacion,
                                this
                        );

                tarjeta.setAlignmentX(
                        java.awt.Component.LEFT_ALIGNMENT
                );

                tarjeta.setMaximumSize(
                        new java.awt.Dimension(
                                Integer.MAX_VALUE,
                                tarjeta.getPreferredSize().height
                        )
                );

                panelMisPublicaciones.add(tarjeta);

                panelMisPublicaciones.add(
                        javax.swing.Box.createVerticalStrut(10)
                );
            }
        }

        panelMisPublicaciones.revalidate();
        panelMisPublicaciones.repaint();
    }

    public void actualizarPublicacionesUsuario() {
        cargarPublicacionesUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMisPublicaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        lblMiperfil = new javax.swing.JLabel();
        lblinfoPerfil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 248, 252));

        jScrollPane1.setBorder(null);

        panelMisPublicaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelMisPublicaciones.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelMisPublicacionesLayout = new javax.swing.GroupLayout(panelMisPublicaciones);
        panelMisPublicaciones.setLayout(panelMisPublicacionesLayout);
        panelMisPublicacionesLayout.setHorizontalGroup(
            panelMisPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        panelMisPublicacionesLayout.setVerticalGroup(
            panelMisPublicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelMisPublicaciones);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 58, 154));
        jLabel1.setText("Mis Publicaciones");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 58, 154));
        lblNombre.setText("Nombre:");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setBorder(null);
        txtNombre.setName(""); // NOI18N

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(0, 58, 154));
        lblCorreo.setText("Correo:");

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setBorder(null);
        txtCorreo.setName(""); // NOI18N

        lblCarrera.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(0, 58, 154));
        lblCarrera.setText("Carrera:");

        txtCarrera.setEditable(false);
        txtCarrera.setBackground(new java.awt.Color(255, 255, 255));
        txtCarrera.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCarrera.setForeground(new java.awt.Color(153, 153, 153));
        txtCarrera.setToolTipText("");
        txtCarrera.setBorder(null);
        txtCarrera.setName(""); // NOI18N

        lblMiperfil.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        lblMiperfil.setForeground(new java.awt.Color(0, 58, 154));
        lblMiperfil.setText("Mi perfil");

        lblinfoPerfil.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblinfoPerfil.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoPerfil.setText("Consulta tu información personal");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profileicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinfoPerfil)
                            .addComponent(lblMiperfil)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCarrera)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMiperfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblinfoPerfil)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(11, 11, 11)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCorreo)
                                .addGap(11, 11, 11)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(lblCarrera)
                        .addGap(11, 11, 11)
                        .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblMiperfil;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblinfoPerfil;
    private javax.swing.JPanel panelMisPublicaciones;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
