/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DTO.PublicacionVista;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author User
 */
public class PublicacionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PublicacionPanel
     */
    private int idPublicacion;
    private PublicacionVista publicacion;

    public PublicacionPanel() {
        initComponents();
    }

    public PublicacionPanel(PublicacionVista publicacion) {
        initComponents();

        this.publicacion = publicacion;
        this.idPublicacion = publicacion.getIdPublicacion();

        lblTitulo.setText(publicacion.getTitulo());
        lblUsuario.setText(publicacion.getNombreUsuario());
        lblCategoria.setText(publicacion.getNombreCategoria());

        if (publicacion.getFecha() != null) {
            DateTimeFormatter formato
                    = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            lblFecha.setText(publicacion.getFecha().format(formato));
        } else {
            lblFecha.setText("Fecha: no disponible");
        }

        txtContenido.setText(publicacion.getContenido());
        txtContenido.setEditable(false);
        txtContenido.setLineWrap(true);
        txtContenido.setWrapStyleWord(true);
        txtContenido.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        btnDetalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(153, 153, 153));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 58, 154));
        lblTitulo.setText("Titulo ");

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(153, 153, 153));
        lblUsuario.setText("Autor");

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(153, 153, 153));
        lblFecha.setText("Fecha");

        lblCategoria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(0, 58, 154));
        lblCategoria.setText("Categoria");

        btnDetalle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnDetalle.setForeground(new java.awt.Color(0, 58, 154));
        btnDetalle.setText("Ver Detalle");
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        txtContenido.setEditable(false);
        txtContenido.setBackground(new java.awt.Color(243, 246, 252));
        txtContenido.setColumns(20);
        txtContenido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtContenido.setLineWrap(true);
        txtContenido.setRows(5);
        txtContenido.setWrapStyleWord(true);
        txtContenido.setBorder(null);
        jScrollPane1.setViewportView(txtContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUsuario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha)
                            .addGap(18, 18, 18)
                            .addComponent(lblCategoria))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblFecha)
                    .addComponent(lblCategoria))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
        if (publicacion == null) {
            return;
        }

        DetallePublicacionForm detalle
                = new DetallePublicacionForm(publicacion);

        detalle.setLocationRelativeTo(
                javax.swing.SwingUtilities
                        .getWindowAncestor(this)
        );

        detalle.setVisible(true);
    }//GEN-LAST:event_btnDetalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
