/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioController;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class RegistroForm extends javax.swing.JFrame {

    private UsuarioController usuarioController;

    /**
     * Creates new form RegistroForm
     */
    public RegistroForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        usuarioController = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmarContrasena = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 251, 252));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 32, 94));
        jLabel1.setText("Crear cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 32, 94));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        txtNombre.setBackground(new java.awt.Color(250, 251, 252));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 256, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 32, 94));
        jLabel3.setText("Correo Electrónico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(250, 251, 252));
        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 256, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 32, 94));
        jLabel4.setText("Carrera");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        cmbCarrera.setForeground(new java.awt.Color(204, 204, 204));
        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su carrera...", "Software", "Tecnologia de la Informacion", "IA", "Ingenieria Civil" }));
        jPanel1.add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 256, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 32, 94));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtContrasena.setBackground(new java.awt.Color(250, 251, 252));
        txtContrasena.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtContrasena.setBorder(null);
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 256, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 32, 94));
        jLabel6.setText("Confirmar Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtConfirmarContrasena.setBackground(new java.awt.Color(250, 251, 252));
        txtConfirmarContrasena.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtConfirmarContrasena.setBorder(null);
        jPanel1.add(txtConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 256, -1));

        btnRegistrarse.setBackground(new java.awt.Color(0, 32, 94));
        btnRegistrarse.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setBorder(null);
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 110, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("¿Ya tienes una cuenta?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        lblIniciarSesion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(0, 0, 255));
        lblIniciarSesion.setText("Iniciar Sesion");
        lblIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 32, 94));
        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 32, 94));
        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 260, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 32, 94));
        jSeparator4.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 32, 94));
        jSeparator5.setMaximumSize(new java.awt.Dimension(32767, 35));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 260, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 450, 480));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        String nombre = txtNombre.getText().trim();
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();
        String confirmarContrasena = new String(txtConfirmarContrasena.getPassword()).trim();
        String carrera = cmbCarrera.getSelectedItem().toString();

        if (nombre.isBlank() || correo.isBlank() || contrasena.isBlank()
                || confirmarContrasena.isBlank()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        if (!usuarioController.validarNombre(nombre)) {
            JOptionPane.showMessageDialog(this,
                    "El nombre solo puede contener letras y espacios.");
            return;
        }

        if (!usuarioController.validarContrasena(contrasena)) {
            JOptionPane.showMessageDialog(this,
                    "La contraseña debe tener al menos 8 caracteres.");
            return;
        }
        if (!usuarioController.validarCorreo(correo)) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese un correo electrónico válido.");
            return;
        }

        if (cmbCarrera.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar una carrera.",
                    "Campo obligatorio",
                    JOptionPane.WARNING_MESSAGE
            );
            cmbCarrera.requestFocus();
            return;
        }
        if (usuarioController.existeCorreo(correo)) {
            JOptionPane.showMessageDialog(this, "El correo ya está registrado.");
            return;
        }

        if (!contrasena.equals(confirmarContrasena)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            return;
        }
        boolean registrado = usuarioController.registrarUsuario(nombre, correo, contrasena, carrera);
        if (registrado) {
            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");
            txtNombre.setText("");
            txtCorreo.setText("");
            txtContrasena.setText("");
            txtConfirmarContrasena.setText("");
            cmbCarrera.setSelectedIndex(0);

            LoginForm login = new LoginForm();
            login.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario.");
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked

    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void lblIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSesionMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JPasswordField txtConfirmarContrasena;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
